CI: Added build pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,9 +1,17 @@
 name: Build
 
-on: [ workflow_call ]
+on:
+  workflow_dispatch:
+    inputs:
+      version:
+        description: New version number
+        type: string
+      commit:
+        description: Commit the new version and create version tag
+        type: boolean
 
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
 
     steps:
@@ -11,20 +19,88 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Setup NodeJS
+        if: ${{ inputs.version }}
         uses: actions/setup-node@v4
         with:
           node-version: '20.x'
 
-      - name: Install dependencies
-        run: npm ci
+      - name: Read package.json
+        if: ${{ inputs.version }}
+        id: manifest
+        uses: zoexx/github-action-json-file-properties@1.0.4
+        with:
+          file_path: package.json
 
-      - name: Build extension
-        run: npm run build
+      # Use Node to determine if the new version number is higher that the current
+      - name: Check version change
+        if: ${{ inputs.version }}
+        id: versionchange
+        run: |
+          node -p "'valid='+('${{ inputs.version }}' > '${{ steps.manifest.outputs.version }}'?'valid':'invalid')" >> $GITHUB_OUTPUT
 
-      - name: Upload build
+      - name: Invalid new version
+        if: ${{ inputs.version && steps.versionchange.outputs.valid != 'valid' }}
+        run: |
+          echo "::error ::The new version number (${{ inputs.version }}) is not higher than the current (${{ steps.manifest.outputs.version }})"
+          exit 1
+
+      # Update the version in the package file
+      - name: Change version
+        if: ${{ inputs.version }}
+        uses: maxgfr/github-change-json@v0.0.25
+        with:
+          key: version
+          value: ${{ inputs.version }}
+          path: package.json
+
+      - name: Upload package.json
         uses: actions/upload-artifact@v4
         with:
-          name: build
-          path: dist/
+          name: package-json
+          path: package.json
           if-no-files-found: error
-          
+
+
+  build:
+    needs: [ prepare ]
+    uses: ./.github/workflows/build-sea.yml
+    with:
+      fetchPackageJson: true
+
+  test-win-x64:
+    needs: [ build ]
+    uses: ./.github/workflows/test-binary.yml
+    with:
+      binaryName: smtp2graph-win-x64.exe
+      platform: windows-latest
+
+  test-linux-x64:
+    needs: [ build ]
+    uses: ./.github/workflows/test-binary.yml
+    with:
+      binaryName: smtp2graph-linux-x64
+      platform: ubuntu-latest
+
+  commit:
+    if: ${{ inputs.version && inputs.commit }}
+    runs-on: ubuntu-latest
+    needs: [test-win-x64, test-linux-x64]
+
+    permissions:
+      contents: write
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download package.json
+        uses: actions/download-artifact@v4
+        with:
+          name: package-json
+
+      - name: Push version bump
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: Version bump
+          file_pattern: package.json
+          tagging_message: v${{ inputs.version }}
